import type { User, Ride } from "./types";

// Mock users (MongoDB-ready structure)
export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    name: "Alex Chen",
    email: "alex.chen@university.edu",
    university: "State University",
    phone: "+1 555-0101",
    bio: "CS senior, often heading to the airport on Fridays.",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "user-2",
    name: "Jordan Smith",
    email: "jordan.smith@university.edu",
    university: "State University",
    bio: "Grad student, grocery runs every Sunday.",
    createdAt: "2025-01-16T09:00:00Z",
    updatedAt: "2025-01-16T09:00:00Z",
  },
  {
    id: "user-3",
    name: "Sam Rivera",
    email: "sam.rivera@university.edu",
    university: "State University",
    createdAt: "2025-01-17T11:00:00Z",
    updatedAt: "2025-01-17T11:00:00Z",
  },
];

// Mock rides (MongoDB-ready structure)
export const createInitialRides = (): Ride[] => {
  const now = new Date().toISOString();
  return [
    {
      id: "ride-1",
      createdByUserId: "user-1",
      creatorName: "Alex Chen",
      creatorEmail: "alex.chen@university.edu",
      startLocation: "Campus Main Gate",
      destination: "Walmart",
      date: "2025-03-20",
      time: "14:00",
      note: "Grocery run, can make a quick stop at Target if needed.",
      price: 0,
      isFree: true,
      availableSeats: 2,
      totalSeats: 3,
      status: "active",
      joinedUserIds: ["user-2"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ride-2",
      createdByUserId: "user-1",
      creatorName: "Alex Chen",
      creatorEmail: "alex.chen@university.edu",
      startLocation: "Student Union",
      destination: "Airport (SFO)",
      date: "2025-03-22",
      time: "06:00",
      note: "Early flight. Share gas and tolls.",
      price: 25,
      isFree: false,
      availableSeats: 1,
      totalSeats: 3,
      status: "active",
      joinedUserIds: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ride-3",
      createdByUserId: "user-2",
      creatorName: "Jordan Smith",
      creatorEmail: "jordan.smith@university.edu",
      startLocation: "North Dorm Lot",
      destination: "Trader Joe's",
      date: "2025-03-18",
      time: "10:00",
      note: "Weekly grocery trip.",
      price: 0,
      isFree: true,
      availableSeats: 0,
      totalSeats: 2,
      status: "full",
      joinedUserIds: ["user-3"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ride-4",
      createdByUserId: "user-3",
      creatorName: "Sam Rivera",
      creatorEmail: "sam.rivera@university.edu",
      startLocation: "Library",
      destination: "Downtown Mall",
      date: "2025-03-25",
      time: "15:30",
      note: "Shopping and food. Back by 8pm.",
      price: 5,
      isFree: false,
      availableSeats: 3,
      totalSeats: 4,
      status: "active",
      joinedUserIds: [],
      createdAt: now,
      updatedAt: now,
    },
  ];
};
